<a href="https://colab.research.google.com/github/deepakdmane/ml/blob/main/data_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# import Libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Import DataSET

In [ ]:
try:
    dataset = pd.read_csv('Data.csv')
    display(df.head())
except FileNotFoundError:
    print("Error: 'Data.csv' not found. Please ensure the file exists in the current directory.")
except pd.errors.EmptyDataError:
    print("Error: 'Data.csv' is empty.")
except pd.errors.ParserError:
    print("Error: 'Data.csv' could not be parsed. Please check the file format.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

An unexpected error occurred: name 'df' is not defined

In [ ]:
# Determine the shape of the DataFrame
print("Shape of the DataFrame:", dataset.shape)

# Examine data types
print("\nData Types:")
print(dataset.dtypes)

# Check for missing values
print("\nMissing Values:")
print(dataset.isnull().sum())

# Descriptive statistics for numerical features
print("\nDescriptive Statistics for Numerical Features:")
print(dataset.describe())

# Explore categorical features
print("\nValue Counts for Categorical Features:")
for col in ['Country', 'Purchased']:
    print(f"\nColumn: {col}")
    print(dataset[col].value_counts())

Shape of the DataFrame: (28, 4)

Data Types:
Country       object
Age            int64
Salary       float64
Purchased     object
dtype: object

Missing Values:
Country      0
Age          0
Salary       7
Purchased    0
dtype: int64

Descriptive Statistics for Numerical Features:
             Age        Salary
count  28.000000     21.000000
mean   33.964286  62828.571429
std     5.757328  25235.790910
min    22.000000  20000.000000
25%    30.250000  40000.000000
50%    34.000000  70000.000000
75%    38.250000  80000.000000
max    43.000000  93400.000000

Value Counts for Categorical Features:

Column: Country
Country
USA          7
Canada       7
UK           7
Australia    7
Name: count, dtype: int64

Column: Purchased
Purchased
Yes    14
No     14
Name: count, dtype: int64

In [ ]:
print(x)

[['USA' 35 75000.0]
 ['Canada' 28 60000.0]
 ['UK' 42 90000.0]
 ['Australia' 31 nan]
 ['USA' 35 75000.0]
 ['Canada' 28 20000.0]
 ['UK' 42 90200.0]
 ['Australia' 31 nan]
 ['USA' 35 72000.0]
 ['Canada' 28 20000.0]
 ['UK' 42 90400.0]
 ['Australia' 31 nan]
 ['USA' 35 40000.0]
 ['Canada' 28 20000.0]
 ['UK' 42 30000.0]
 ['Australia' 31 nan]
 ['USA' 35 70000.0]
 ['Canada' 28 80000.0]
 ['UK' 42 34000.0]
 ['Australia' 31 nan]
 ['USA' 35 65000.0]
 ['Canada' 28 64000.0]
 ['UK' 42 93400.0]
 ['Australia' 31 nan]
 ['USA' 33 73000.0]
 ['Canada' 22 67000.0]
 ['UK' 43 90400.0]
 ['Australia' 37 nan]]

In [ ]:
print(y)

['Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes'
 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No'
 'Yes' 'No']

In [ ]:
dataset.columns[:-1]

Index(['Country', 'Age', 'Salary'], dtype='object')

In [ ]:
x_df = pd.DataFrame(x, columns=dataset.columns[:-1])

In [ ]:
x_df

      Country Age   Salary
0         USA  35  75000.0
1      Canada  28  60000.0
2          UK  42  90000.0
3   Australia  31      NaN
4         USA  35  75000.0
5      Canada  28  20000.0
6          UK  42  90200.0
7   Australia  31      NaN
8         USA  35  72000.0
9      Canada  28  20000.0
10         UK  42  90400.0
11  Australia  31      NaN
12        USA  35  40000.0
13     Canada  28  20000.0
14         UK  42  30000.0
15  Australia  31      NaN
16        USA  35  70000.0
17     Canada  28  80000.0
18         UK  42  34000.0
19  Australia  31      NaN
20        USA  35  65000.0
21     Canada  28  64000.0
22         UK  42  93400.0
23  Australia  31      NaN
24        USA  33  73000.0
25     Canada  22  67000.0
26         UK  43  90400.0
27  Australia  37      NaN

In [ ]:
missing_counts = x_df.isnull().sum()
missing_counts

Country    0
Age        0
Salary     7
dtype: int64

# Taking Case of Missing data

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [ ]:
x

array([['USA', 35.0, 75000.0],
       ['Canada', 28.0, 60000.0],
       ['UK', 42.0, 90000.0],
       ['Australia', 31.0, 62828.57142857143],
       ['USA', 35.0, 75000.0],
       ['Canada', 28.0, 20000.0],
       ['UK', 42.0, 90200.0],
       ['Australia', 31.0, 62828.57142857143],
       ['USA', 35.0, 72000.0],
       ['Canada', 28.0, 20000.0],
       ['UK', 42.0, 90400.0],
       ['Australia', 31.0, 62828.57142857143],
       ['USA', 35.0, 40000.0],
       ['Canada', 28.0, 20000.0],
       ['UK', 42.0, 30000.0],
       ['Australia', 31.0, 62828.57142857143],
       ['USA', 35.0, 70000.0],
       ['Canada', 28.0, 80000.0],
       ['UK', 42.0, 34000.0],
       ['Australia', 31.0, 62828.57142857143],
       ['USA', 35.0, 65000.0],
       ['Canada', 28.0, 64000.0],
       ['UK', 42.0, 93400.0],
       ['Australia', 31.0, 62828.57142857143],
       ['USA', 33.0, 73000.0],
       ['Canada', 22.0, 67000.0],
       ['UK', 43.0, 90400.0],
       ['Australia', 37.0, 62828.57142857143]], dtype=object)

# Encode Categorical Data

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(x))

In [ ]:
print(X)

[[0.0 0.0 0.0 1.0 35.0 75000.0]
 [0.0 1.0 0.0 0.0 28.0 60000.0]
 [0.0 0.0 1.0 0.0 42.0 90000.0]
 [1.0 0.0 0.0 0.0 31.0 62828.57142857143]
 [0.0 0.0 0.0 1.0 35.0 75000.0]
 [0.0 1.0 0.0 0.0 28.0 20000.0]
 [0.0 0.0 1.0 0.0 42.0 90200.0]
 [1.0 0.0 0.0 0.0 31.0 62828.57142857143]
 [0.0 0.0 0.0 1.0 35.0 72000.0]
 [0.0 1.0 0.0 0.0 28.0 20000.0]
 [0.0 0.0 1.0 0.0 42.0 90400.0]
 [1.0 0.0 0.0 0.0 31.0 62828.57142857143]
 [0.0 0.0 0.0 1.0 35.0 40000.0]
 [0.0 1.0 0.0 0.0 28.0 20000.0]
 [0.0 0.0 1.0 0.0 42.0 30000.0]
 [1.0 0.0 0.0 0.0 31.0 62828.57142857143]
 [0.0 0.0 0.0 1.0 35.0 70000.0]
 [0.0 1.0 0.0 0.0 28.0 80000.0]
 [0.0 0.0 1.0 0.0 42.0 34000.0]
 [1.0 0.0 0.0 0.0 31.0 62828.57142857143]
 [0.0 0.0 0.0 1.0 35.0 65000.0]
 [0.0 1.0 0.0 0.0 28.0 64000.0]
 [0.0 0.0 1.0 0.0 42.0 93400.0]
 [1.0 0.0 0.0 0.0 31.0 62828.57142857143]
 [0.0 0.0 0.0 1.0 33.0 73000.0]
 [0.0 1.0 0.0 0.0 22.0 67000.0]
 [0.0 0.0 1.0 0.0 43.0 90400.0]
 [1.0 0.0 0.0 0.0 37.0 62828.57142857143]]

# Encoding the Dependant Variables

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0])

# Splitting data into training data and test data

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [ ]:
X_train, X_test, y_train, y_test

(array([[0.0, 0.0, 1.0, 0.0, 42.0, 93400.0],
        [0.0, 0.0, 1.0, 0.0, 42.0, 90400.0],
        [0.0, 1.0, 0.0, 0.0, 28.0, 64000.0],
        [0.0, 0.0, 0.0, 1.0, 35.0, 75000.0],
        [0.0, 0.0, 1.0, 0.0, 42.0, 90000.0],
        [1.0, 0.0, 0.0, 0.0, 31.0, 62828.57142857143],
        [0.0, 0.0, 1.0, 0.0, 42.0, 90200.0],
        [0.0, 0.0, 1.0, 0.0, 42.0, 34000.0],
        [0.0, 1.0, 0.0, 0.0, 28.0, 20000.0],
        [1.0, 0.0, 0.0, 0.0, 31.0, 62828.57142857143],
        [0.0, 1.0, 0.0, 0.0, 22.0, 67000.0],
        [0.0, 1.0, 0.0, 0.0, 28.0, 60000.0],
        [0.0, 0.0, 0.0, 1.0, 35.0, 70000.0],
        [0.0, 0.0, 0.0, 1.0, 35.0, 75000.0],
        [1.0, 0.0, 0.0, 0.0, 31.0, 62828.57142857143],
        [1.0, 0.0, 0.0, 0.0, 37.0, 62828.57142857143],
        [0.0, 0.0, 1.0, 0.0, 43.0, 90400.0],
        [0.0, 1.0, 0.0, 0.0, 28.0, 20000.0],
        [0.0, 0.0, 0.0, 1.0, 35.0, 72000.0],
        [0.0, 0.0, 0.0, 1.0, 35.0, 40000.0],
        [1.0, 0.0, 0.0, 0.0, 31.0, 62828.57142857143],
        [0.0, 1.0, 0.0, 0.0, 28.0, 20000.0]], dtype=object),
 array([[0.0, 0.0, 0.0, 1.0, 33.0, 73000.0],
        [0.0, 1.0, 0.0, 0.0, 28.0, 80000.0],
        [1.0, 0.0, 0.0, 0.0, 31.0, 62828.57142857143],
        [0.0, 0.0, 0.0, 1.0, 35.0, 65000.0],
        [0.0, 0.0, 1.0, 0.0, 42.0, 30000.0],
        [1.0, 0.0, 0.0, 0.0, 31.0, 62828.57142857143]], dtype=object),
 array([1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0]),
 array([1, 0, 0, 1, 1, 0]))

# Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [ ]:
print(X_train)

[[0.0 0.0 1.0 -0.5423261445466405 1.3252522947496297 1.3449193470178973]
 [0.0 0.0 1.0 -0.5423261445466405 1.3252522947496297 1.2122877003473311]
 [0.0 1.0 0.0 -0.5423261445466405 -1.0341564149780338 0.04512920964634858]
 [0.0 0.0 0.0 1.8439088914585777 0.14554793988579798 0.5314452474384246]
 [0.0 0.0 1.0 -0.5423261445466405 1.3252522947496297 1.1946034807912556]
 [1.0 0.0 0.0 -0.5423261445466405 -0.5285688343221059
  -0.006660290482158265]
 [0.0 0.0 1.0 -0.5423261445466405 1.3252522947496297 1.2034455905692933]
 [0.0 0.0 1.0 -0.5423261445466405 1.3252522947496297 -1.2811872570593132]
 [0.0 1.0 0.0 -0.5423261445466405 -1.0341564149780338 -1.9001349415219555]
 [1.0 0.0 0.0 -0.5423261445466405 -0.5285688343221059
  -0.006660290482158265]
 [0.0 1.0 0.0 -0.5423261445466405 -2.0453315762898896 0.17776085631691477]
 [0.0 1.0 0.0 -0.5423261445466405 -1.0341564149780338
  -0.13171298591440633]
 [0.0 0.0 0.0 1.8439088914585777 0.14554793988579798 0.31039250298748094]
 [0.0 0.0 0.0 1.8439088914585777 0.14554793988579798 0.5314452474384246]
 [1.0 0.0 0.0 -0.5423261445466405 -0.5285688343221059
  -0.006660290482158265]
 [1.0 0.0 0.0 -0.5423261445466405 0.4826063269897499
  -0.006660290482158265]
 [0.0 0.0 1.0 -0.5423261445466405 1.4937814883016056 1.2122877003473311]
 [0.0 1.0 0.0 -0.5423261445466405 -1.0341564149780338 -1.9001349415219555]
 [0.0 0.0 0.0 1.8439088914585777 0.14554793988579798 0.39881360076785843]
 [0.0 0.0 0.0 1.8439088914585777 0.14554793988579798 -1.015923963718181]
 [1.0 0.0 0.0 -0.5423261445466405 -0.5285688343221059
  -0.006660290482158265]
 [0.0 1.0 0.0 -0.5423261445466405 -1.0341564149780338 -1.9001349415219555]]

In [ ]:
print(X_test)

[[0.0 0.0 0.0 1.8439088914585777 -0.19151044721815397 0.44302414965804715]
 [0.0 1.0 0.0 -0.5423261445466405 -1.0341564149780338 0.7524979918893683]
 [1.0 0.0 0.0 -0.5423261445466405 -0.5285688343221059
  -0.006660290482158265]
 [0.0 0.0 0.0 1.8439088914585777 0.14554793988579798 0.0893397585365373]
 [0.0 0.0 1.0 -0.5423261445466405 1.3252522947496297 -1.4580294526200683]
 [1.0 0.0 0.0 -0.5423261445466405 -0.5285688343221059
  -0.006660290482158265]]